# Configurações básicas do Upptime - ajuste 'owner' e 'repo' para seu usuário e repositório
owner: dan77632             # Seu usuário GitHub
repo: status-do-site        # Nome do repositório onde o Upptime está configurado

# Lista de sites para monitorar
sites:
  - name: Google
    url: https://www.google.com

  - name: Wikipédia
    url: https://en.wikipedia.org

  - name: Hacker News
    url: https://news.ycombinator.com

  - name: Prefeitura Banabuiu       # Nome mais descritivo para facilitar entendimento
    url: https://banabuiu.ce.gov.br
    port: 443                      # HTTPS padrão, pode deixar explícito
    check: "http"                  # Verificação HTTP padrão

  - name: Teste IPv6
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

# Configurações da página de status pública gerada
status-website:
  cname: dan77632.github.io/site-status  # Seu domínio público GitHub Pages (ajuste se for outro)
  # baseUrl: /status-do-site              # Descomente e ajuste se usar domínio padrão do GitHub

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  name: Status do Site - Upptime

  introTitle: "**Upptime** - Monitoramento aberto de status de sites, totalmente via GitHub."
  introMessage: |
    Esta é uma página de status que usa dados em **tempo real** do nosso repositório [GitHub](https://github.com/dan77632/status-do-site).  
    Sem necessidade de servidores adicionais — apenas GitHub Actions, Issues e Pages.  
    [**Configure o seu gratuitamente!**](https://github.com/upptime/upptime)

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dan77632/status-do-site
